services:
  - type: web
    name: payslip-system
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://trail_db_user:ZFjmUOMVSdatCOsq@cluster0.h1pqrer.mongodb.net/?retryWrites=true&w=majority
      - key: DB_NAME
        value: payslip_system
